### ISSUE TITLE
Implementation logos are not displayed correctly on mobile

### ISSUE THREAD

**Issue by tomkerkhove** [oam-dev/oam-dev.github.io#23]
In #21 I've introduced a list of current and upcoming implementations next to Rudr.

Unfortunately it looks like I broke the section as logos are not displayed correctly.

![Screenshot_20200122-072353](https://user-images.githubusercontent.com/4345663/72870365-4cfdc480-3ce8-11ea-8706-eea8e8484a67.png)

**Comment by vturecek** [comment]
I took the logos out for the narrow view for now.
