### ISSUE TITLE
Looks like oam.dev is down

### ISSUE THREAD

**Issue by kvaleev** [oam-dev/oam-dev.github.io#24]
The https://oam.dev website looks like out of service, it still responses on ping, but trying to open it in Chrome I get an _ERR_CONNECTION_REFUSED_ error.

**Comment by flynnduism** [comment]
Thanks for flagging @kvaleev . It's working now again.

✅ oam.dev
✅ oam-dev.github.io
❌ openappmodel.io _(https error) *_

`*` I think we discontinued this one anyway? 

As the main url is back online, seems like this was a short outage. Marking this closed.
