### ISSUE TITLE
https://oam.dev broken

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/oam-dev.github.io#25]
seems the ssl cert is out of date

**Comment by flynnduism** [comment]
Seems to be working again, not sure what caused this... 
possibly a temp outage with LetsEncrypt or GitHub pages.

**Comment by wonderflow** [comment]
I think we could setup some monitoring for it.

**Comment by wonderflow** [comment]
I've tested and add a notification to my slack if the site failed again. Would you like to setup something like it and get noticed？
https://github.com/wonderflow/oam-dev.github.io/blob/dev/.github/workflows/blank.yml

**Comment by flynnduism** [comment]
Good idea @wonderflow to configure an uptime monitor for alerts!

Closing this issue as the site is not broken.
