### ISSUE TITLE
oam.dev should have Community Meeting links for both Asia Pacific and North America

### ISSUE THREAD

**Issue by abchow** [oam-dev/oam-dev.github.io#27]
Currently, the Community Meeting link in oam.dev is the meeting link for Asia Pacific community meeting.   

https://us04web.zoom.us/j/661104426  

We should add the North America community meeting link in there and label them accordingly.  
Here is the meeting link for North America community meeting.  

https://zoom.us/j/271516061

**Comment by resouer** [comment]
Fixed!
