### ISSUE TITLE
Can't read text on iPhone and Android devices due to images hiding text

### ISSUE THREAD

**Issue by prasek** [oam-dev/oam-dev.github.io#30]
@vturecek not sure if this was a result of recent changes

Android

![image](https://user-images.githubusercontent.com/284840/82391190-8d9aef80-99f5-11ea-9a77-fc96571080a3.png)

iPhone

![image](https://user-images.githubusercontent.com/284840/82391426-19ad1700-99f6-11ea-981d-1b74bceab12f.png)

**Comment by resouer** [comment]
It has been fixed.
