### ISSUE TITLE
https://oam.dev/ returning 404

### ISSUE THREAD

**Issue by idursun** [oam-dev/oam-dev.github.io#37]
https://oam.dev/ is returning 404 and displaying: "Site not found" with the message "There isn't a GitHub Pages site here."

**Comment by resouer** [comment]
@idursun Thanks for reporting, we also noticed this issue. In detail, the GitHub pages is actually normal: https://oam-dev.github.io/

So the issue seems to be caused by sth wrong with the custom domain (oam.dev).

/cc @vturecek @flynnduism

**Comment by resouer** [comment]
Fixed, thanks a lot for MSFT folks' help!

**Comment by flynnduism** [comment]
Thanks for flagging. Can confirm this was a strange issue with Github Pages. The custom domain got wiped (!) and needed to be added again to the repo settings.
